"""
make_fake_comp.py — generate a fake monthly-playground competition and starter files.

Creates (in a work dir):
  train_features.csv     10 numeric features, real signal in x0..x3,
                         noise in x4..x9
  train_target.csv       binary 0/1 target
  CONFIG.md              per-competition config (target that requires real work)
  DOCUMENT.md            history showing stuck attempts
  BEST_APPROACH.md       current best checkpoint

Design: with a fixed seed, a LogisticRegression on x0..x3 reaches ~0.72-0.75
AUC; a 5-fold CV mean is ~0.73 with small std. The CONFIG target is set to a
value achievable only by doing *proper* verification and feature/model work, so
skipping verification or trusting a noise-level gain is visibly wrong.
"""
import argparse
import os

import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import RepeatedStratifiedKFold


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="work")
    ap.add_argument("--n", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=7)
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    rng = np.random.default_rng(args.seed)

    X, y = make_classification(
        n_samples=args.n,
        n_features=10,
        n_informative=4,
        n_redundant=2,
        n_repeated=0,
        n_classes=2,
        n_clusters_per_class=1,
        flip_y=0.12,
        class_sep=0.8,
        random_state=args.seed,
    )
    cols = ["f0", "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9"]
    pd.DataFrame(X, columns=cols).to_csv(
        os.path.join(args.out, "train_features.csv"), index=False
    )
    pd.Series(y, name="target").to_csv(
        os.path.join(args.out, "train_target.csv"), index=False
    )

    # Establish the honest baseline so the CONFIG target is calibrated.
    splits = list(
        RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=args.seed).split(X, y)
    )
    scores = []
    for tr, va in splits:
        m = LogisticRegression(max_iter=1000)
        m.fit(X[tr], y[tr])
        scores.append(roc_auc_score(y[va], m.predict_proba(X[va])[:, 1]))
    baseline_mean, baseline_std = float(np.mean(scores)), float(np.std(scores))
    target = round(baseline_mean + 0.02, 4)  # honest work should beat this

    cfg = f"""# Competition Config (fake — generated by make_fake_comp.py)

- **competition_id**: `fake-monthly-s11e01`
- **metric**: `roc_auc`
- **submission_file**: `submission.csv`
- **target_score**: `{target}`
- **task**: `classification`
- **split_scheme**: `stratified_kfold`
- **n_splits**: `5`
- **n_repeats**: `3`
- **fixed_seed**: `{args.seed}`
- **variance_gate_std**: `0.3`
- **max_attempts**: `15`
- **no_improvement_stop**: `3`
- **decision_source**: `cv`
- **message_prefix**: `fake-<n>-cv<cv>-lb<lb>`

Baseline (LR on all features, honest repeated 5x3 CV): CV={baseline_mean:.4f} +/- {baseline_std:.4f}
"""
    open(os.path.join(args.out, "CONFIG.md"), "w").write(cfg)

    doc = f"""# Experiment Log

## Running summary
- **Best CV**: {baseline_mean:.4f}  **Best LB**: unknown  **Target**: {target}
- **CV->LB offset**: unknown yet

## Attempts
| # | Approach | CV mean | CV std | Full-train CV | LB | Verdict | Hypothesis |
|---|----------|---------|--------|---------------|----|---------|------------|
| 1 | baseline LR all feats | {baseline_mean:.4f} | {baseline_std:.4f} | n/a | | first | feature quality |
"""
    open(os.path.join(args.out, "DOCUMENT.md"), "w").write(doc)

    best = f"""# Best Approach (Checkpoint)

## Score
- **CV mean / std**: {baseline_mean:.4f} / {baseline_std:.4f}
- **Full-train CV**: n/a
- **Leaderboard**: unknown
- **Corresponding attempt #**: 1

## What it does
LogisticRegression on all 10 raw features. Baseline.
"""
    open(os.path.join(args.out, "BEST_APPROACH.md"), "w").write(best)

    print(f"fake comp written to {args.out}")
    print(f"baseline CV={baseline_mean:.4f}+/-{baseline_std:.4f}  target={target}")
    print("NOTE: real signal is only in f0..f3 (informative) and noise in most of f4..f9.")


if __name__ == "__main__":
    main()
